import CompassIcon13px from "../../../assets/svg/CompassIcon13px";
import Button from "../../../components/Button";
import styles from "./styles.module.scss";

const PromoSection = () => {
  return (
    <div className={styles.promoSection}>
      <div className={styles.promoSectionText}>
        This was intelligently
        <br /> generated by Compass
      </div>
      <Button
        href="https://compasswearable.com/"
        icon={
          <CompassIcon13px fill="#fff" style={{ transform: "scale(1.2)" }} />
        }
      >
        Learn more
      </Button>
    </div>
  );
};

export default PromoSection;
